// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvcswkvuomgiyokjbvii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52Y3N3a3Z1b21naXlva2pidmlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzcxOTAsImV4cCI6MjA3NDAxMzE5MH0.AojAwcCayIXzqrcnWe5LHfHS7Jt5tm3z1YxJkJ9c9CM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});